<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OxyPlot.OpenXml</RootNamespace>
    <AssemblyName>OxyPlot.OpenXml</AssemblyName>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);1573;1591;1712;CA1416</NoWarn>
    <AssemblyTitle>OxyPlot.OpenXml</AssemblyTitle>
    <Description>OxyPlot OpenXml export library</Description>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\Output\NET45\</OutputPath>
    <DocumentationFile>..\..\Output\NET45\OxyPlot.OpenXml.XML</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs">
      <Link>Properties\GlobalAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot.Wpf\OxyPlot.Wpf.core.csproj" />
    <ProjectReference Include="..\OxyPlot\OxyPlot.core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\packages\StyleCop.Analyzers.Unstable.1.2.0.435\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\packages\StyleCop.Analyzers.Unstable.1.2.0.435\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.435" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
  </ItemGroup>
</Project>