<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OxyPlot.Wpf</RootNamespace>
    <AssemblyName>OxyPlot.Wpf</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <StyleCopTreatErrorsAsWarnings>false</StyleCopTreatErrorsAsWarnings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PackageId>evoleap.OxyPlot.Wpf.core</PackageId>
    <Authors>evoleap</Authors>
    <Description>Modified version of OxyPlot. OxyPlot is an open source plotting library for .NET 8. This package contains the custom control for WPF applications.</Description>
    <PackageTags>wpf plotting plot charting chart</PackageTags>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn),1573,1591,1712</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>..\..\Output\NET45\OxyPlot.Wpf.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\..\Output\NET45\</OutputPath>
    <DefineConstants>TRACE;WPF</DefineConstants>
    <DocumentationFile>..\..\Output\NET45\OxyPlot.Wpf.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>OxyPlot.Wpf.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\GlobalAssemblyInfo.cs">
      <Link>Properties\GlobalAssemblyInfo.cs</Link>
    </Compile>
    <None Include="RenderContexts\GeometryRenderContext.cs" />
    <None Include="RenderContexts\DrawingRenderContext.cs" />
    <None Include="PlotFrame.cs" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OxyPlot\OxyPlot.core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\packages\StyleCop.Analyzers.Unstable.1.2.0.435\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\packages\StyleCop.Analyzers.Unstable.1.2.0.435\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.435" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="PlotFrame.cs" />
    <Compile Remove="RenderContexts\DrawingRenderContext.cs" />
    <Compile Remove="RenderContexts\GeometryRenderContext.cs" />
  </ItemGroup>
</Project>